version: '3'
services:
  mysql:
    image: mysql:5.7
    restart: on-failure
    command: --init-file /data/application/inti.sql
    environment:
      - MYSQL_DATABASE=test_bd
      - MYSQL_ROOT_PASSWORD=''
      - MYSQL_USER=django_user
      - MYSQL_PASSWORD=12345
    volumes:
      - "./init.sql:/data/application/inti.sql"

  pet_shop:
    build: .
    command: python3 /app/manage.py runserver 0.0.0.0:8888
#    volumes:
#      - "./shop_rest_api/migrations/:/app/shop_rest_api/migrations/"
#      - "./app/shop_rest_api/migrations/:/shop_rest_api/migrations"
    ports:
      - "8888:8888"
    depends_on:
      - mysql
