# Generated by Django 2.2.6 on 2019-12-11 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('price', models.FloatField()),
                ('pet_type', models.CharField(max_length=50)),
            ],
        ),
    ]
